Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Style/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Style/SpaceAroundOperators:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
